language: objective-c

os: osx
osx_image: xcode10.1

xcode_scheme: Scout
xcode_workspace: Scout.xcworkspace
xcode_destination: platform=iOS Simulator,OS=11.0.1,name=iPhone X

cache: cocoapods

before_install:
  - brew upgrade --cleanup
  - pod update

before_script:
  - swiftlint

# TODO: Remove this once a test target has been created.
script: set -o pipefail && xcodebuild -workspace Scout.xcworkspace -scheme Scout -destination platform\=iOS\ Simulator,OS\=11.0.1,name\=iPhone\ X build | xcpretty
